config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :bugs
  end
  resources :users
  root 'users#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :project_name, presence: true
  has_many :bugs, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  def index; end

  def show
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.new
    @users_array = User.all.map { |user| [user.email, user.email] }
  end

  def create
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.new(bug_params)
    if @bug.save
      redirect_to project_bug_path(@project, @bug)
    else
      render 'new'
    end
  end

  def edit
   end

  def update
   end

  def destroy
    @project = Project.find(params[:id])
    @bug = @project.bugs.find(params[:id])
    @bug.destroy
    redirect_to project_path(@project)
  end

  private

  def bug_params
    params.require(:bug).permit(:buglist, :assigned_to)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:project_name)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bugs_helper.rb
# frozen_string_literal: true

module BugsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/bugs/_form.slim
= form_with model: [@project,@project.bugs.build], local: true do |form|
	- if @project.errors.any?
		#error_explanation
			h2 one error prohibited this article from being saved:
			-@project.bugs.errors.full_messages.each do |msg|
				= msg
        br
	= form.label :bugs
	= form.text_field :buglist
	br
	= form.label :assigned_to
	= form.select :assigned_to, options_for_select(@users_array)
	br
	= form.submit

app/views/bugs/new.slim
h1 Add bugs
= render 'form'

app/views/bugs/show.slim
strong project:
= @project.project_name
br
strong bug:
= @bug.buglist
br
br
= link_to 'Back', project_path(@project), class:'btn btn-primary'

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title BugTrackingProject
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .notice=notice
    .alert=alert
    .container
      = yield

app/views/projects/_form.slim
= form_with model: @project, local: true do |form|
	- if @project.errors.any?
		#error_explanation
			h2 one error prohibited this article from being saved:
			-@project.errors.full_messages.each do |msg|
				= msg
	br
	= form.label :project_name
	= form.text_field :project_name
	br
	= form.submit

app/views/projects/edit.slim
h1 Edit project
= render 'form'
br
= link_to 'back', projects_path

app/views/projects/index.slim
h1 Bug tracking tool
div class="d-flex justify-content-between"
  = link_to 'New project', new_project_path, class: 'btn btn-primary'
  = link_to 'sign_out', destroy_user_session_path, method: :delete, class: "btn btn-primary"

br
table class='table table-striped'
  tr
    th Project
    th colspan="3" action
  -@projects.each do |project|
    tr
      td= project.project_name
      td= link_to 'Show', project_path(project), class: 'btn btn-info'
      td= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning'
      td= link_to 'Delete', project_path(project), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'

app/views/projects/new.slim
h1 New project
= render 'form'
br
= link_to 'Back', projects_path, class: 'btn btn-primary'

app/views/projects/show.slim
table class='table table-striped'
  tr
    th project name
    th bugs
    th assigned to
    th colspan="3" action
  -@project.bugs.each do |bug|
    tr
      td= @project.project_name
      td= bug.buglist
      td= bug.assigned_to
      td= link_to 'Edit bug', edit_project_bug_path(@project,bug), class: 'btn btn-warning'
      td= link_to 'Delete bug', project_bug_path(bug), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'


br
= link_to 'Add bugs',new_project_bug_path(@project), class:'btn btn-primary'
br
br
= link_to 'Back', projects_path, class:'btn btn-primary'

app/views/users/home.slim
.container
  h1 WELCOME TO THE BUG TRACKING APP
  - if user_signed_in?
    - if current_user.admin?
      br
      p You are admin,you can invite users
      br
      = link_to 'send invitation', new_user_invitation_path, class: 'btn btn-primary'
    br
    br
    = link_to 'All projects', projects_path, class: 'btn btn-primary'
  - else
    = link_to 'sign_in', new_user_session_path, class: 'btn btn-primary'

app/views/users/index.slim
h1 i am index